# Generated by Django 3.2 on 2021-05-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurzy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kurz',
            new_name='Kurzy',
        ),
    ]
