# Generated by Django 3.2 on 2021-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracniZnacka', models.CharField(max_length=7)),
                ('pocetKilometru', models.DateTimeField()),
                ('datumKontroly', models.DateTimeField()),
                ('znackaTypVozidla', models.CharField(max_length=1000)),
            ],
        ),
    ]
