# Generated by Django 3.2 on 2021-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jmeno', models.CharField(max_length=20)),
                ('Prijmeni', models.CharField(max_length=20)),
                ('CisloRidicskehoPRukazu', models.CharField(max_length=20)),
                ('datumNarozeni', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='datumKontroly',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='pocetKilometru',
            field=models.IntegerField(),
        ),
    ]
