# Generated by Django 3.2 on 2021-05-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20210502_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZacatekVypujcky', models.DateTimeField()),
                ('KonecVypujcky', models.DateTimeField()),
                ('CenaVypujcky', models.IntegerField()),
            ],
        ),
    ]
